name: sfc
channels:
    - conda-forge
dependencies:
    - python=3.8
    - numpy
    - scipy
    - matplotlib
    - xarray
    - netcdf4
    - pyyaml
    - pandas
    - scikit-learn
    - pytest
    - jupyter
    - dask
    - distributed
    - pip
    - numba
    - pvlib-python
    - tqdm
    - pip:
        - tensorflow==2.4.1
