#!/bin/bash
#PBS -N mlsl_a
#PBS -A NWSA0002
#
# Each array subjob will be assigned a single CPU with 4 GB of memory
###PBS -l select=1:ncpus=1:ngpus=1:mem=4GB
#PBS -l select=1:ncpus=1:mem=4GB
#PBS -l walltime=00:20:00
#PBS -q casper
#
# Specify that the GPUs will be V100s
###PBS -l gpu_type=v100
#
#PBS -M hmarrero@ucar.edu
#PBS -o "${TMPDIR}/pbs_out_${name}--kfold-${PBS_ARRAY_INDEX}-test.txt"
#
# Request 10 subjobs
#PBS -J 0-2
#PBS -j oe
#PBS -r y 
### line needed for array job to work (received from hpc help desk)





### Set TMPDIR as recommended
#export TMPDIR=/glade/scratch/$USER/tmp
#export TMPDIR=../../data/tmp
export TMPDIR=/glade/campaign/ral/wsap/oracleMLSL/data/tmp
mkdir -p $TMPDIR

# LOAD NEEDED MODULES
module load conda
#conda activate ../../data/conda-envs/ral
conda activate /glade/campaign/ral/wsap/oracleMLSL/data/conda-envs/ral
export CUDNN_PATH=${CONDA_PREFIX}/lib/python3.10/site-packages/nvidia/cudnn
export TENSORRT_PATH=${CONDA_PREFIX}/lib/python3.10/site-packages/tensorrt_libs
export LD_LIBRARY_PATH=${CUDNN_PATH}/lib:${TENSORRT_PATH}:${CONDA_PREFIX}/lib/:${LD_LIBRARY_PATH}
export XLA_FLAGS=--xla_gpu_cuda_data_dir=${CONDA_PREFIX}

# For CUDA Aware MPI support
export OMPI_MCA_opal_cuda_support=true

# For TF optimizations, see https://github.com/NVIDIA/DeepLearningExamples/issues/57
export TF_GPU_THREAD_MODE=gpu_private
export TF_GPU_THREAD_COUNT=2 # 2 (default) or sometimes 4 seems a little better

cd ../scripts/

# Access command line arguments
name="offshore_surface_layer_training_mvco_McCandless"
python ../summer_work_2024/createKfoldYaml.py "../config/$name.yml" >& $TMPDIR/createKfold_out_${name}--kfold-${PBS_ARRAY_INDEX}-test.txt 

filename="../../data/model_output/${name}/${name}--kfold-${PBS_ARRAY_INDEX}.yml"
mkdir -p $filename
mkdir -p "../../data/model_output/${name}/"

python train_offshore_models_mvco.py $filename >& $TMPDIR/train_out_${name}--kfold-${PBS_ARRAY_INDEX}-test.txt 

cd ../summer_work_2024/
python o_mvco_model_analysis.py $filename >& $TMPDIR/graph_out_${name}--kfold-${PBS_ARRAY_INDEX}-test.txt 

# Check if var equals a number
#if [ "$PBS_ARRAY_INDEX" -eq 9 ]; then
#    python average_metrics.py "../config/$name.yml" >& $TMPDIR/metrics_out_${name}--kfold-${PBS_ARRAY_INDEX}-test.txt 
#
#fi
