data_file: ../hector/mvco_mlsl_qc.csv
derived_columns:
- temperature:18.4_m:K
- water_sfc_temperature:0_m:K
- pressure:18.4_m:hPa
- potential_temperature:18.4_m:K
- skin_virtual_potential_temperature:0_m:K
- mixing_ratio:0_m:g_kg-1
- mixing_ratio:18.4_m:g_kg-1
- relative_humidity:18.4_m:%
- wave_direction:0_m:degrees
- wave_height:0_m:m
- wave_period:0_m:s
- wave_phase_speed:0_m:m_s-1
- near_surf_current:0_m:m_s-1
- near_surf_current_dir:0_m:deg
- wind_speed:18.4_m:m_s-1
- wind_direction:18.4_m:degrees
- angle_between_wind_wave:0_m:degrees
- u_wind:18.4_m:m_s-1
- v_wind:18.4_m:m_s-1
- bulk_richardson:18.4_m:none
- u_w:18.4_m:m2_s-2
- v_w:18.4_m:m2_s-2
file_name: offshore_surface_layer_training_mvco--kfold-5
filter_counter_gradient: 0
input_columns:
  heat_flux:
  - zenith:0_m:degrees
  - azimuth:0_m:degrees
  - water_sfc_temperature:0_m:K
  - pressure:18.4_m:hPa
  - mixing_ratio:18.4_m:g_kg-1
  - relative_humidity:18.4_m:%
  - wave_direction:0_m:degrees
  - wave_height:0_m:m
  - wave_period:0_m:s
  - angle_between_wind_wave:0_m:degrees
  - wind_speed:18.4_m:m_s-1
  - wind_direction:18.4_m:degrees
  - bulk_richardson:18.4_m:none
  momentum_flux:
  - zenith:0_m:degrees
  - azimuth:0_m:degrees
  - water_sfc_temperature:0_m:K
  - pressure:18.4_m:hPa
  - mixing_ratio:18.4_m:g_kg-1
  - relative_humidity:18.4_m:%
  - wave_direction:0_m:degrees
  - wave_height:0_m:m
  - wave_period:0_m:s
  - angle_between_wind_wave:0_m:degrees
  - wind_speed:18.4_m:m_s-1
  - wind_direction:18.4_m:degrees
  - bulk_richardson:18.4_m:none
k_fold_cross_validation:
  N: 10
  devVar: kfold
  k: 5
model_config:
  neural_network:
    activation: tanh
    batch_size: 32
    epochs: 1000
    hidden_layers: 1
    hidden_neurons: 64
    l2_weight: 0.0
    lr: 0.001
    min_delta: 0
    patience: 50
  random_forest:
    max_features: 10
    max_leaf_nodes: 1024
    n_estimators: 100
    n_jobs: 4
model_metric_types:
- mean_squared_error
- mean_absolute_error
- mean_error
- pearson_r2
out_dir: ../hector/model_QC_--kfold-5
output_columns:
  heat_flux: heat_flux:18.4_m:degrees_C_m_s-1
  momentum_flux: momentum_flux:18.4_m:m2_s-2
output_types:
- momentum_flux
- heat_flux
stability_column: bulk_richardson:18.4_m:none
train_test_split_date: '2010-10-01'
