#
#
#
file_name: "exp_heightDependent_rf_ltd_noDir"
data_file: "../../data/mvco_mlsl_qc.csv"
out_dir: "../../data/model_output/"
filter_counter_gradient: 0
train_test_split_date: "2010-10-01"
output_types: ['momentum_flux', 'heat_flux']
model_metric_types: ["mean_squared_error", "mean_absolute_error", "mean_error","pearson_r2"]
input_columns:
  momentum_flux:
    [
    #"zenith:0_m:degrees",
    #"azimuth:0_m:degrees",
    #"GHI:0_m:W_m-2",
    "pressure:18.4_m:hPa",
    #"sea_surface_pressure:0_m:hPa",
    "relative_humidity:18.4_m:%",
    #"temperature:18.4_m:K",
    "potential_temperature:18.4_m:K", 
    #"water_sfc_temperature:0_m:K",
    #"mixing_ratio:0_m:g_kg-1",
    "mixing_ratio:18.4_m:g_kg-1",
    #"skin_virtual_potential_temperature:0_m:K",
    # "wave_direction:0_m:degrees",
    "wave_height:0_m:m",
    #"wave_period:0_m:s",
    #"wave_phase_speed:0_m:m_s-1",
    # "u_wave:0_m:m_s-1",
    # "v_wave:0_m:m_s-1",
    #'cos_wave_direction:0_m:radians',
    #'sin_wave_direction:0_m:radians',
    #"near_surf_current_u:0_m:m_s-1",
    #"near_surf_current_v:0_m:m_s-1",
    #"near_surf_current:0_m:m_s-1",
    #"near_surf_current_dir:0_m:deg",
    #"sin_near_surf_current_dir:0_m:radians",
    #"cos_near_surf_current_dir:0_m:radians",
    #"u_wind:18.4_m:m_s-1",
    #"v_wind:18.4_m:m_s-1",
    #'cos_wind_direction:18.4_m:radians',
    #'sin_wind_direction:18.4_m:radians',
    "wind_speed:18.4_m:m_s-1",
    #"wind_direction:18.4_m:degrees",
    #"angle_between_wind_wave:0_m:degrees",
    "bulk_richardson:18.4_m:none"
    #"dT_dz:18.4_m:K_m-1",
    #"dSpeed_dz:18.4_m:s-1",
    #"dPotTemp_dz:18.4_m:K_m-1",
    #"dMixingRatio_dz:18.4_m:g_kg-1_m-1"
    # "u_w:18.4_m:m2_s-2",
    # "v_w:18.4_m:m2_s-2",
    # "T_w:18.4_m:C_m_s-2",
    # "heat_flux:18.4_m:degrees_C_m_s-1",
    # "momentum_flux:18.4_m:m2_s-2",
    # "friction_velocity:18.4_m:m_s-1",
    # "temperature_scale:18.4_m:K",
    # "MOST_momentum_flux:18.4_m:m2_s-2",
    # "MOST_heat_flux:18.4_m:degrees_K_m_s-1",
    # "MOST_chopped_momentum_flux:18.4_m:m2_s-2",
    # "MOST_chopped_heat_flux:18.4_m:degrees_K_m_s-1",
    # "MOST_rounded_momentum_flux:18.4_m:m2_s-2",
    # "MOST_rounded_heat_flux:18.4_m:degrees_K_m_s-1",
    # 'log_momentum_flux',
    # 'exp_momentum_flux'
    ]
  heat_flux: 
    [
    #"zenith:0_m:degrees",
    #"azimuth:0_m:degrees",
    #"GHI:0_m:W_m-2",
    "pressure:18.4_m:hPa",
    #"sea_surface_pressure:0_m:hPa",
    "relative_humidity:18.4_m:%",
    #"temperature:18.4_m:K",
    "potential_temperature:18.4_m:K", 
    #"water_sfc_temperature:0_m:K",
    #mixing_ratio:0_m:g_kg-1",
    "mixing_ratio:18.4_m:g_kg-1",
    #"skin_virtual_potential_temperature:0_m:K",
    # "wave_direction:0_m:degrees",
    "wave_height:0_m:m",
    #"wave_period:0_m:s",
    #"wave_phase_speed:0_m:m_s-1",
    #"u_wave:0_m:m_s-1",
    #"v_wave:0_m:m_s-1",
    #'cos_wave_direction:0_m:radians',
    #'sin_wave_direction:0_m:radians',
    #"near_surf_current_u:0_m:m_s-1",
    #"near_surf_current_v:0_m:m_s-1",
    #"near_surf_current:0_m:m_s-1",
    # "near_surf_current_dir:0_m:deg",
    #"sin_near_surf_current_dir:0_m:radians",
    #"cos_near_surf_current_dir:0_m:radians",
    #"u_wind:18.4_m:m_s-1",
    #"v_wind:18.4_m:m_s-1",
    #'cos_wind_direction:18.4_m:radians',
    #'sin_wind_direction:18.4_m:radians',
    "wind_speed:18.4_m:m_s-1",
    # "wind_direction:18.4_m:degrees",
    #"angle_between_wind_wave:0_m:degrees",
    "bulk_richardson:18.4_m:none"
    #"dT_dz:18.4_m:K_m-1",
    #"dSpeed_dz:18.4_m:s-1",
    #"dPotTemp_dz:18.4_m:K_m-1",
    #"dMixingRatio_dz:18.4_m:g_kg-1_m-1"
    # "u_w:18.4_m:m2_s-2",
    # "v_w:18.4_m:m2_s-2",
    # "T_w:18.4_m:C_m_s-2",
    # "heat_flux:18.4_m:degrees_C_m_s-1",
    # "momentum_flux:18.4_m:m2_s-2",
    # "friction_velocity:18.4_m:m_s-1",
    # "temperature_scale:18.4_m:K",
    # "MOST_momentum_flux:18.4_m:m2_s-2",
    # "MOST_heat_flux:18.4_m:degrees_K_m_s-1",
    # "MOST_chopped_momentum_flux:18.4_m:m2_s-2",
    # "MOST_chopped_heat_flux:18.4_m:degrees_K_m_s-1",
    # "MOST_rounded_momentum_flux:18.4_m:m2_s-2",
    # "MOST_rounded_heat_flux:18.4_m:degrees_K_m_s-1",
    # 'log_momentum_flux',
    # 'exp_momentum_flux'
    ]
output_columns:
  momentum_flux: "momentum_flux:18.4_m:m2_s-2" # mf units
  heat_flux: "heat_flux:18.4_m:degrees_C_m_s-1" # hf units
  
derived_columns: [
'temperature:18.4_m:K',
'water_sfc_temperature:0_m:K',
'pressure:18.4_m:hPa', 
'potential_temperature:18.4_m:K',
'skin_virtual_potential_temperature:0_m:K', 
'mixing_ratio:0_m:g_kg-1',
'mixing_ratio:18.4_m:g_kg-1',
'relative_humidity:18.4_m:%',
'wave_direction:0_m:degrees', 
'wave_height:0_m:m', 
'wave_period:0_m:s',
'wave_phase_speed:0_m:m_s-1', 
'near_surf_current:0_m:m_s-1',
'near_surf_current_dir:0_m:deg', 
'wind_speed:18.4_m:m_s-1',
'wind_direction:18.4_m:degrees', 
'angle_between_wind_wave:0_m:degrees',
'u_wind:18.4_m:m_s-1',
'v_wind:18.4_m:m_s-1', 
'bulk_richardson:18.4_m:none', 
'u_w:18.4_m:m2_s-2',
'v_w:18.4_m:m2_s-2',
"dT_dz:18.4_m:K_m-1",
"dSpeed_dz:18.4_m:s-1",
"MOST_momentum_flux:18.4_m:m2_s-2",
"MOST_heat_flux:18.4_m:degrees_K_m_s-1",
"MOST_chopped_momentum_flux:18.4_m:m2_s-2",
"MOST_chopped_heat_flux:18.4_m:degrees_K_m_s-1",
"MOST_rounded_momentum_flux:18.4_m:m2_s-2",
"MOST_rounded_heat_flux:18.4_m:degrees_K_m_s-1"
]
stability_column: "bulk_richardson:18.4_m:none"

k_fold_cross_validation:
  devVar: 'kfold'
  N: 10 
  k: 0
  holdout_ratio: 0.1
  scramble: False

model_config:
  random_forest:
    n_estimators: 100
    max_features: 10 
    n_jobs: 4
    max_leaf_nodes: 1024
#  neural_network:
#    hidden_layers: 5
#    hidden_neurons: 128
#    batch_size: 32
#    epochs: 100
#    lr: 0.001
#    activation: tanh
#    l2_weight: 0.0
#    min_delta: 0.01
#    patience: 25
#    early_stop: True 
