data_file: "/glade/p/cisl/aiml/fasteddy/idaho_derived_data_20210720.csv"
out_dir: "/glade/p/cisl/aiml/fasteddy/idaho_surface_layer_models_20201203/"
filter_counter_gradient: 0
train_test_split_date: "2017-01-01"
output_types: ["friction_velocity", "kinematic_sensible_heat_flux", "kinematic_latent_heat_flux"]
model_metric_types: ["mean_squared_error", "mean_absolute_error", "mean_error", "pearson_r2", "hellinger_distance"]
input_columns:
  friction_velocity: ['wind_speed:10_m:m_s-1',
                      'potential_temperature_skin_change:10_m:K_m-1',
                      'bulk_richardson:10_m:None',
                      'mixing_ratio_skin_change:2_m:g_kg-1_m-1',
                      ]
  kinematic_sensible_heat_flux: ['wind_speed:10_m:m_s-1',
                      'potential_temperature_skin_change:10_m:K_m-1',
                      'bulk_richardson:10_m:None',
                      'mixing_ratio_skin_change:2_m:g_kg-1_m-1',
                      ]
  kinematic_latent_heat_flux: [   'wind_speed:10_m:m_s-1',
                      'bulk_richardson:10_m:None',
                      'mixing_ratio_skin_change:2_m:g_kg-1_m-1',
                      ]
output_columns:
  friction_velocity: "friction_velocity:surface:m_s-1"
  kinematic_sensible_heat_flux: "kinematic_sensible_heat_flux:surface:K_m_s-1"
  kinematic_latent_heat_flux: "kinematic_latent_heat_flux:surface:g_kg-1_m_s-1"
derived_columns: ["sensible_heat_flux:surface:W_m-2",
                  "latent_heat_flux:surface:W_m-2",
                  "bulk_richardson:10_m:None",
                  "air_density:10_m:kg_m-3",
                  ]
stability_column: "bulk_richardson:10_m:None"
model_config:
  neural_network_1:
    hidden_layers: 2
    hidden_neurons: 64
    batch_size: 128
    epochs: 20
    lr: 0.0001
    activation: "selu"
    l2_weight: 1.0e-6
    verbose: 1
  neural_network_2:
    hidden_layers: 2
    hidden_neurons: 64
    batch_size: 128
    epochs: 20
    lr: 0.0001
    activation: "selu"
    l2_weight: 1.0e-6
    verbose: 1
  neural_network_3:
    hidden_layers: 2
    hidden_neurons: 64
    batch_size: 128
    epochs: 20
    lr: 0.0001
    activation: "selu"
    l2_weight: 1.0e-6
    verbose: 1
  neural_network_4:
    hidden_layers: 2
    hidden_neurons: 64
    batch_size: 128
    epochs: 20
    lr: 0.0001
    activation: "selu"
    l2_weight: 1.0e-6
    verbose: 1
  neural_network_5:
    hidden_layers: 2
    hidden_neurons: 64
    batch_size: 128
    epochs: 20
    lr: 0.0001
    activation: "selu"
    l2_weight: 1.0e-6
    verbose: 1
  neural_network_6:
    hidden_layers: 2
    hidden_neurons: 64
    batch_size: 128
    epochs: 20
    lr: 0.0001
    activation: "selu"
    l2_weight: 1.0e-6
    verbose: 1
  neural_network_7:
    hidden_layers: 2
    hidden_neurons: 64
    batch_size: 128
    epochs: 20
    lr: 0.0001
    activation: "selu"
    l2_weight: 1.0e-6
    verbose: 1
  neural_network_8:
    hidden_layers: 2
    hidden_neurons: 64
    batch_size: 128
    epochs: 20
    lr: 0.0001
    activation: "selu"
    l2_weight: 1.0e-6
    verbose: 1
  neural_network_9:
    hidden_layers: 2
    hidden_neurons: 64
    batch_size: 128
    epochs: 20
    lr: 0.0001
    activation: "selu"
    l2_weight: 1.0e-6
    verbose: 1
  neural_network_10:
    hidden_layers: 2
    hidden_neurons: 64
    batch_size: 128
    epochs: 20
    lr: 0.0001
    activation: "selu"
    l2_weight: 1.0e-6
    verbose: 1
  neural_network_11:
    hidden_layers: 2
    hidden_neurons: 64
    batch_size: 128
    epochs: 20
    lr: 0.0001
    activation: "selu"
    l2_weight: 1.0e-6
    verbose: 1
  neural_network_12:
    hidden_layers: 2
    hidden_neurons: 64
    batch_size: 128
    epochs: 20
    lr: 0.0001
    activation: "selu"
    l2_weight: 1.0e-6
    verbose: 1
  neural_network_13:
    hidden_layers: 2
    hidden_neurons: 64
    batch_size: 128
    epochs: 20
    lr: 0.0001
    activation: "selu"
    l2_weight: 1.0e-6
    verbose: 1
  neural_network_14:
    hidden_layers: 2
    hidden_neurons: 64
    batch_size: 128
    epochs: 20
    lr: 0.0001
    activation: "selu"
    l2_weight: 1.0e-6
    verbose: 1
  neural_network_15:
    hidden_layers: 2
    hidden_neurons: 64
    batch_size: 128
    epochs: 20
    lr: 0.0001
    activation: "selu"
    l2_weight: 1.0e-6
    verbose: 1
  neural_network_16:
    hidden_layers: 2
    hidden_neurons: 64
    batch_size: 128
    epochs: 20
    lr: 0.0001
    activation: "selu"
    l2_weight: 1.0e-6
    verbose: 1
  neural_network_17:
    hidden_layers: 2
    hidden_neurons: 64
    batch_size: 128
    epochs: 20
    lr: 0.0001
    activation: "selu"
    l2_weight: 1.0e-6
    verbose: 1
  neural_network_18:
    hidden_layers: 2
    hidden_neurons: 64
    batch_size: 128
    epochs: 20
    lr: 0.0001
    activation: "selu"
    l2_weight: 1.0e-6
    verbose: 1
  neural_network_19:
    hidden_layers: 2
    hidden_neurons: 64
    batch_size: 128
    epochs: 20
    lr: 0.0001
    activation: "selu"
    l2_weight: 1.0e-6
    verbose: 1
  neural_network_20:
    hidden_layers: 2
    hidden_neurons: 64
    batch_size: 128
    epochs: 20
    lr: 0.0001
    activation: "selu"
    l2_weight: 1.0e-6
    verbose: 1
  neural_network_21:
    hidden_layers: 2
    hidden_neurons: 64
    batch_size: 128
    epochs: 20
    lr: 0.0001
    activation: "selu"
    l2_weight: 1.0e-6
    verbose: 1
  neural_network_22:
    hidden_layers: 2
    hidden_neurons: 64
    batch_size: 128
    epochs: 20
    lr: 0.0001
    activation: "selu"
    l2_weight: 1.0e-6
    verbose: 1
  neural_network_23:
    hidden_layers: 2
    hidden_neurons: 64
    batch_size: 128
    epochs: 20
    lr: 0.0001
    activation: "selu"
    l2_weight: 1.0e-6
    verbose: 1
  neural_network_24:
    hidden_layers: 2
    hidden_neurons: 64
    batch_size: 128
    epochs: 20
    lr: 0.0001
    activation: "selu"
    l2_weight: 1.0e-6
    verbose: 1
  neural_network_25:
    hidden_layers: 2
    hidden_neurons: 64
    batch_size: 128
    epochs: 20
    lr: 0.0001
    activation: "selu"
    l2_weight: 1.0e-6
    verbose: 1
  neural_network_26:
    hidden_layers: 2
    hidden_neurons: 64
    batch_size: 128
    epochs: 20
    lr: 0.0001
    activation: "selu"
    l2_weight: 1.0e-6
    verbose: 1
  neural_network_27:
    hidden_layers: 2
    hidden_neurons: 64
    batch_size: 128
    epochs: 20
    lr: 0.0001
    activation: "selu"
    l2_weight: 1.0e-6
    verbose: 1
  neural_network_28:
    hidden_layers: 2
    hidden_neurons: 64
    batch_size: 128
    epochs: 20
    lr: 0.0001
    activation: "selu"
    l2_weight: 1.0e-6
    verbose: 1
  neural_network_29:
    hidden_layers: 2
    hidden_neurons: 64
    batch_size: 128
    epochs: 20
    lr: 0.0001
    activation: "selu"
    l2_weight: 1.0e-6
    verbose: 1
  neural_network_30:
    hidden_layers: 2
    hidden_neurons: 64
    batch_size: 128
    epochs: 20
    lr: 0.0001
    activation: "selu"
    l2_weight: 1.0e-6
    verbose: 1