#data_file: "/d1/mlsurfacelayer/data/fino/derived/fino_derived.csv"
data_file: "/d1/mlsurfacelayer/data/fino/derived/fino_derived30Min.csv"
out_dir: "/d1/mlsurfacelayer/data/fino/models"
filter_counter_gradient: 0
train_test_split_date: "2010-10-01"
output_types: ["friction_velocity40","temp_scale40"]
#output_types: ["friction_velocity"]
#model_metric_types: ["mean_squared_error"]
model_metric_types: ["mean_squared_error", "mean_absolute_error", "mean_error"]
input_columns:
  friction_velocity40: [ 
#"global_horizontal_irradiance:30_m:W_m-2",
"zenith:0_m:degrees",
#"azimuth:0_m:degrees",
#"temperature:40_m:K",
#"temperature:60_m:K",
#"temperature:80_m:K",
"water_sfc_temperature:0_m:K",
#"pressure:0_m:hPa",
#"pressure:40_m:hPa",
#"pressure:60_m:hPa",
#"pressure:80_m:hPa",
"potential_temperature:40_m:K",
#"potential_temperature:60_m:K",
#"potential_temperature:80_m:K",
#"skin_virtual_potential_temperature:0_m:K",
#"mixing_ratio:0_m:g_kg-1",
"mixing_ratio:40_m:g_kg-1",
#"mixing_ratio:60_m:g_kg-1",
#"mixing_ratio:80_m:g_kg-1",
"relative_humidity:40_m:%",
#"relative_humidity:60_m:%",
#"relative_humidity:80_m:%",
"wave_dir_linear_interp:0_m:degrees",
"wave_height:0_m:m",
"wave_period:0_m:s",
#"wave_phase_speed:0_m:m_s-1",
"wind_speed:40_m:m_s-1",
#"wind_direction:40_m:degrees",
#"wind_speed:60_m:m_s-1",
#"wind_direction:60_m:degrees",
#"wind_speed:80_m:m_s-1",
#"wind_direction:80_m:degrees",
"u_wind:40_m:m_s-1",
"v_wind:40_m:m_s-1",
#"u_wind:60_m:m_s-1",
#"v_wind:60_m:m_s-1",
#"u_wind:80_m:m_s-1",
#"v_wind:80_m:m_s-1",
"bulk_richardson:40_m:none",
#"bulk_richardson:60_m:none",
#"bulk_richardson:80_m:none",
"potential_temperature_gradient:20_m:K_m-1",
#"potential_temperature_gradient:40_m:K_m-1",
"wind_speed_gradient:20_m:s-1"
#"wind_speed_gradient:40_m:s-1"
#"sensible_heat_flux:40_m:W_m-2"
]
  temp_scale40: [
"global_horizontal_irradiance:30_m:W_m-2",
"zenith:0_m:degrees",
"azimuth:0_m:degrees",
#"temperature:40_m:K",
#"temperature:60_m:K",
#"temperature:80_m:K",
"water_sfc_temperature:0_m:K",
#"pressure:0_m:hPa",
#"pressure:40_m:hPa",
#"pressure:60_m:hPa",
#"pressure:80_m:hPa",
"potential_temperature:40_m:K",
#"potential_temperature:60_m:K",
#"potential_temperature:80_m:K",
#"skin_virtual_potential_temperature:0_m:K",
#"mixing_ratio:0_m:g_kg-1",
"mixing_ratio:40_m:g_kg-1",
#"mixing_ratio:60_m:g_kg-1",
#"mixing_ratio:80_m:g_kg-1",
"relative_humidity:40_m:%",
#"relative_humidity:60_m:%",
#"relative_humidity:80_m:%",
"wave_dir_linear_interp:0_m:degrees",
"wave_height:0_m:m",
"wave_period:0_m:s",
#"wave_phase_speed:0_m:m_s-1",
"wind_speed:40_m:m_s-1",
#"wind_direction:40_m:degrees",
#"wind_speed:60_m:m_s-1",
#"wind_direction:60_m:degrees",
#"wind_speed:80_m:m_s-1",
#"wind_direction:80_m:degrees",
"u_wind:40_m:m_s-1",
"v_wind:40_m:m_s-1",
#"u_wind:60_m:m_s-1",
#"v_wind:60_m:m_s-1",
#"u_wind:80_m:m_s-1",
#"v_wind:80_m:m_s-1",
"bulk_richardson:40_m:none",
#"bulk_richardson:60_m:none",
#"bulk_richardson:80_m:none",
"potential_temperature_gradient:20_m:K_m-1",
#"potential_temperature_gradient:40_m:K_m-1",
"wind_speed_gradient:20_m:s-1"
#"wind_speed_gradient:40_m:s-1"
#"sensible_heat_flux:40_m:W_m-2"
] 

  friction_velocity60: [
"temperature:60_m:K",
"water_sfc_temperature:0_m:K",
"pressure:60_m:hPa",
"potential_temperature:60_m:K",
"relative_humidity:60_m:%",
#"wave_dir:0_m:degrees",
"cos_wave_dir_nearest_interp:0_m:degrees",
"wave_height:0_m:m",
"wave_period:0_m:s",
#"wind_speed:40_m:m_s-1",
#"wind_direction:40_m:degrees",
"u_wind:60_m:m_s-1",
"v_wind:60_m:m_s-1",
"bulk_richardson:60_m:none",
"potential_temperature_gradient:20_m:K_m-1",
"wind_speed_gradient:20_m:s-1",
"sensible_heat_flux:40_m:W_m-2"]
  friction_velocity80: [
"temperature:80_m:K",
"water_sfc_temperature:0_m:K",
"pressure:80_m:hPa",
"potential_temperature:80_m:K",
"relative_humidity:80_m:%",
#"wave_dir:0_m:degrees",
"cos_wave_dir_nearest_interp:0_m:degrees",
"wave_height:0_m:m",
"wave_period:0_m:s",
#"wind_speed:40_m:m_s-1",
#"wind_direction:40_m:degrees",
"u_wind:80_m:m_s-1",
"v_wind:80_m:m_s-1",
"bulk_richardson:80_m:none",
"potential_temperature_gradient:40_m:K_m-1",
"wind_speed_gradient:40_m:s-1",
"sensible_heat_flux:40_m:W_m-2"]


output_columns:
  friction_velocity40: "friction_velocity:40_m:m_s-1"
  temp_scale40: "temperature_scale:40_m:K"
  
derived_columns: ["TempScaleMOST", 
                  "TempScaleMOST3",
                  "MOSTustar",
                  "MOSTustar3",
                  "L3",
                  "L",
'global_horizontal_irradiance:30_m:W_m-2',
"zenith:0_m:degrees",
"azimuth:0_m:degrees",
"temperature:40_m:K",
"temperature:60_m:K",
"temperature:80_m:K",
"water_sfc_temperature:0_m:K",
"pressure:0_m:hPa",
"pressure:40_m:hPa",
"pressure:60_m:hPa",
"pressure:80_m:hPa",
"potential_temperature:40_m:K",
"potential_temperature:60_m:K",
"potential_temperature:80_m:K",
"skin_virtual_potential_temperature:0_m:K",
"mixing_ratio:0_m:g_kg-1",
"mixing_ratio:40_m:g_kg-1",
"mixing_ratio:60_m:g_kg-1",
"mixing_ratio:80_m:g_kg-1",
"relative_humidity:40_m:%",
"relative_humidity:60_m:%",
"relative_humidity:80_m:%",
"wave_dir_linear_interp:0_m:degrees",
"wave_height:0_m:m",
"wave_period:0_m:s",
"wave_phase_speed:0_m:m_s-1",
"wind_speed:40_m:m_s-1",
"wind_direction:40_m:degrees",
"wind_speed:60_m:m_s-1",
"wind_direction:60_m:degrees",
"wind_speed:80_m:m_s-1",
"wind_direction:80_m:degrees",
"u_wind:40_m:m_s-1",
"v_wind:40_m:m_s-1",
"u_wind:60_m:m_s-1",
"v_wind:60_m:m_s-1",
"u_wind:80_m:m_s-1",
"v_wind:80_m:m_s-1",
"bulk_richardson:40_m:none",
"bulk_richardson:60_m:none",
"bulk_richardson:80_m:none",
"potential_temperature_gradient:20_m:K_m-1",
"potential_temperature_gradient:40_m:K_m-1",
"wind_speed_gradient:20_m:s-1",
"wind_speed_gradient:40_m:s-1",
"sensible_heat_flux:40_m:W_m-2"
]
stability_column: "bulk_richardson:40_m:none"
model_config:
  random_forest:
    n_estimators: 100
    max_features: 10 
    n_jobs: 4
    max_leaf_nodes: 1024
  neural_network:
    hidden_layers: 3 
    hidden_neurons: 64 
    batch_size: 512
    epochs: 50 
    lr: 0.0001
    activation: tanh
    l2_weight: 0.0
