#
#
#
file_name: "offshore_surface_layer_training_mvco"
data_file: "../hector/mvco_mlsl_qc.csv"
out_dir: "../hector/model_QC_"
filter_counter_gradient: 0
train_test_split_date: "2010-10-01"
#output_types: ['friction_velocity', 'temp_scale', 'heat_flux']
output_types: ['momentum_flux', 'heat_flux']
model_metric_types: ["mean_squared_error", "mean_absolute_error", "mean_error","pearson_r2"]
input_columns:
  momentum_flux: [ 
"zenith:0_m:degrees",
"azimuth:0_m:degrees",
"water_sfc_temperature:0_m:K",
# "pressure:12_m:hPa",
"pressure:18.4_m:hPa",
# "mixing_ratio:12_m:g_kg-1",
"mixing_ratio:18.4_m:g_kg-1",
# "relative_humidity:12_m:%",
"relative_humidity:18.4_m:%",
"wave_direction:0_m:degrees",
"wave_height:0_m:m",
"wave_period:0_m:s",
"angle_between_wind_wave:0_m:degrees",
"wind_speed:18.4_m:m_s-1",
"wind_direction:18.4_m:degrees",
# "bulk_richardson:12_m:none"
"bulk_richardson:18.4_m:none"
#"temperature:12_m:K",
#"potential_temperature:12_m:K",
#"skin_virtual_potential_temperature:0_m:K",
#"mixing_ratio:0_m:g_kg-1",
#"wave_phase_speed:0_m:m_s-1",
]
  heat_flux: [
"zenith:0_m:degrees",
"azimuth:0_m:degrees",
"water_sfc_temperature:0_m:K",
# "pressure:12_m:hPa",
"pressure:18.4_m:hPa",
# "mixing_ratio:12_m:g_kg-1",
"mixing_ratio:18.4_m:g_kg-1",
# "relative_humidity:12_m:%",
"relative_humidity:18.4_m:%",
"wave_direction:0_m:degrees",
"wave_height:0_m:m",
"wave_period:0_m:s",
"angle_between_wind_wave:0_m:degrees",
"wind_speed:18.4_m:m_s-1",
"wind_direction:18.4_m:degrees",
# "bulk_richardson:12_m:none"
"bulk_richardson:18.4_m:none"
#"temperature:12_m:K",
#"potential_temperature:12_m:K",
#"skin_virtual_potential_temperature:0_m:K",
#"mixing_ratio:0_m:g_kg-1",
#"wave_phase_speed:0_m:m_s-1",
#"sensible_heat_flux:12_m:W_m-2"
]
output_columns:
  momentum_flux: "momentum_flux:18.4_m:m2_s-2" # mf units
  heat_flux: "heat_flux:18.4_m:degrees_C_m_s-1" # hf units
  
derived_columns: [
# "TempScaleMOST", 
# "MOSTustar",
# "L",


# 'temperature:12_m:K', 
'temperature:18.4_m:K',
'water_sfc_temperature:0_m:K',
# 'pressure:12_m:hPa', 
'pressure:18.4_m:hPa', 
# 'potential_temperature:12_m:K',
'potential_temperature:18.4_m:K',
'skin_virtual_potential_temperature:0_m:K', 
'mixing_ratio:0_m:g_kg-1',
# 'mixing_ratio:12_m:g_kg-1', 
'mixing_ratio:18.4_m:g_kg-1', 
# 'relative_humidity:12_m:%',
'relative_humidity:18.4_m:%',
'wave_direction:0_m:degrees', 
'wave_height:0_m:m', 
'wave_period:0_m:s',
'wave_phase_speed:0_m:m_s-1', 

'near_surf_current:0_m:m_s-1',
'near_surf_current_dir:0_m:deg', 

'wind_speed:18.4_m:m_s-1',
'wind_direction:18.4_m:degrees', 
'angle_between_wind_wave:0_m:degrees',
'u_wind:18.4_m:m_s-1',
'v_wind:18.4_m:m_s-1', 
# 'bulk_richardson:12_m:none', 
'bulk_richardson:18.4_m:none', 
'u_w:18.4_m:m2_s-2',
'v_w:18.4_m:m2_s-2',
#'friction_velocity:18.4_m:m_s-1',
#'kinematic_sensible_heat_flux:18.4_m:K_m_s-1',
#'temperature_scale:18.4_m:K'

# added derivative below
"dt/dz",
"Speed/z",
"du/dz", # 'U/z' 
"dv/dz" # 'V/z' 
]
# stability_column: "bulk_richardson:12_m:none"
stability_column: "bulk_richardson:18.4_m:none"

k_fold_cross_validation:
  devVar: 'kfold'
  N: 10
  k: 0
  holdout_ratio: 0.1
  scramble: True

model_config:
  random_forest:
    n_estimators: 100
    max_features: 10 
    n_jobs: 4
    max_leaf_nodes: 1024
  neural_network:
    # hidden_layers: 5 
    hidden_layers: 1 
    hidden_neurons: 64 
    batch_size: 32
    epochs:  1000
    lr: 0.001
    activation: tanh
    l2_weight: 0.0
    min_delta: 0.01
    patience: 25
